import React from 'react'
import Head from 'next/head'
import Controls from '../components/Controls'
import Cube from '../components/Cube'

export default function Home() {
  const [rotation, setRotation] = React.useState({ x: 0, y: 0, z: 0 })

  const rotateCube = ({ x, y, z }: { x: number, y: number, z: number }): void => {
    setRotation((prevRotation: { x: number; y: number; z: number }) => ({
      x: x ? prevRotation.x + x : prevRotation.x,
      y: y ? prevRotation.y + y : prevRotation.y,
      z: z ? prevRotation.z + z : prevRotation.z,
    }))
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Controls rotateCube={rotateCube} />
        <Cube rotation={rotation} />
      </main>
    </>
  )
}