import React from 'react'
import Head from 'next/head'
import Game from '@/components/Game'

export default function Home() {
  const canvasRef = React.useRef<HTMLCanvasElement | null>(null)
  const [canvas, setCanvas] = React.useState<HTMLCanvasElement | null>(null)

  React.useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    else setCanvas(canvas)

  }, [canvasRef])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <canvas ref={canvasRef} onContextMenu={(e) => e.preventDefault()} style={{ width: "100vw", height: "100vh", background: 'black' }} />
        {canvas && <Game canvas={canvas} />}
      </main>
    </>
  )
}